[test]
preload = ["./test/preload.ts"]
coverage = true
coverageReporters = ["text", "lcov", "html"]
coverageDirectory = "coverage"
coverageThreshold = { global = { branches = 70, functions = 80, lines = 80, statements = 80 } }